In [ ]:
!pip install -U -q PyDrive

In [ ]:
import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
# Рисовать графики сразу же
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')  # Красивые графики
plt.rcParams['figure.figsize'] = (15, 5)  # Размер картинок

In [ ]:
# choose a local (colab) directory to store the data.
local_download_path = ''
try:
    os.makedirs(local_download_path)
except: pass

In [ ]:
# 2. Auto-iterate using the query syntax
#    https://developers.google.com/drive/v2/web/search-parameters
file_list = drive.ListFile(
    {'q': "'1VVxKv6Hz6ux7MPGuh5YJqExeehfbr2t6' in parents"}).GetList()  #use your own folder ID here
file_list

In [ ]:
fname = 'kulturdata.zip'
f_ = drive.CreateFile({'id': '1VVxKv6Hz6ux7MPGuh5YJqExeehfbr2t6'})
f_.GetContentFile(fname)

In [ ]:
!unzip kulturdata.zip

Archive:  kulturdata.zip
   creating: kulturdata/
  inflating: kulturdata/Classificator_hachaton.csv
  inflating: kulturdata/Pupil_hackaton.csv
  inflating: kulturdata/meropr.csv
  inflating: kulturdata/vyd1.csv
  inflating: kulturdata/MegaRelation_hackaton.csv
  inflating: kulturdata/services_hackaton.csv
  inflating: kulturdata/eksemplar1.csv
  inflating: kulturdata/org_hackaton.csv
  inflating: kulturdata/katal.csv
  inflating: kulturdata/request_hackaton.csv
  inflating: kulturdata/chytatel.csv
  inflating: kulturdata/eksemplar2.csv
  inflating: kulturdata/vyd2.csv

In [ ]:
os.getcwd()

'/content'

In [ ]:
!ls -l kulturdata/

total 781204
-rw-r--r-- 1 root root   8914534 Oct 31 18:44 chytatel.csv
-rw-r--r-- 1 root root     34558 Oct 23 13:01 Classificator_hachaton.csv
-rw-r--r-- 1 root root  54986640 Oct 31 18:36 eksemplar1.csv
-rw-r--r-- 1 root root  56638240 Oct 31 18:42 eksemplar2.csv
-rw-r--r-- 1 root root 218904136 Oct 31 18:47 katal.csv
-rw-r--r-- 1 root root 106193722 Oct 23 12:55 MegaRelation_hackaton.csv
-rw-r--r-- 1 root root  40647959 Oct 31 18:40 meropr.csv
-rw-r--r-- 1 root root    156450 Oct 23 13:00 org_hackaton.csv
-rw-r--r-- 1 root root  77897051 Oct 23 12:49 Pupil_hackaton.csv
-rw-r--r-- 1 root root  48056134 Oct 23 13:00 request_hackaton.csv
-rw-r--r-- 1 root root   5992574 Oct 23 12:59 services_hackaton.csv
-rw-r--r-- 1 root root  89677253 Oct 31 18:46 vyd1.csv
-rw-r--r-- 1 root root  91825070 Oct 31 18:44 vyd2.csv

In [ ]:
eksemplar1 = pd.read_csv("kulturdata/eksemplar1.csv")
meropr = pd.read_csv("kulturdata/meropr.csv")
eksemplar2 = pd.read_csv("kulturdata/eksemplar2.csv")
vyd2 = pd.read_csv("kulturdata/vyd2.csv")
chytatel = pd.read_csv("kulturdata/chytatel.csv")
vyd1 = pd.read_csv("kulturdata/vyd1.csv")
katal = pd.read_csv("kulturdata/katal.csv")
MegaRelation_hackaton = pd.read_csv("kulturdata/MegaRelation_hackaton.csv", sep=';')
services_hackaton = pd.read_csv("kulturdata/services_hackaton.csv", sep=';')
org_hackaton = pd.read_csv("kulturdata/org_hackaton.csv", sep=';')
request_hackaton = pd.read_csv("kulturdata/request_hackaton.csv", sep=';')
Classificator_hachaton = pd.read_csv("kulturdata/Classificator_hachaton.csv", sep=';')
Pupil_hackaton = pd.read_csv("kulturdata/Pupil_hackaton.csv", sep=';')

In [ ]:
n=30

In [ ]:
Pupil_hackaton.head(n)

    id_ученика  возраст      пол
0            1     12.0  Женский
1            2     12.0  Женский
2            3     12.0  Женский
3            4     11.0  Женский
4            5     12.0  Женский
5            6     12.0  Женский
6            7     12.0  Женский
7            8     12.0  Женский
8            9     12.0  Женский
9           10     11.0  Женский
10          11     12.0  Мужской
11          12     11.0  Мужской
12          13     13.0  Женский
13          14     12.0  Женский
14          15     11.0  Женский
15          16     12.0  Женский
16          17     12.0  Женский
17          18     12.0  Женский
18          19     12.0  Женский
19          20     12.0  Женский
20          21     13.0  Женский
21          22     12.0  Женский
22          23     12.0  Женский
23          24     12.0  Женский
24          25     12.0  Мужской
25          26     13.0  Женский
26          27     11.0  Женский
27          28     12.0  Женский
28          29     12.0  Женский
29          30     11.0  Женский

In [ ]:
Classificator_hachaton.head(n)

    id_классификатора  ...                        Наименование
0             3002985  ...                           Автошкола
1             3002986  ...                            Автоклуб
2             3002987  ...          Правила дорожного движения
3             3002988  ...                       Юный водитель
4             3002989  ...                         Архитектура
5             3002990  ...                  Основы архитектуры
6             3002991  ...                     Военная история
7             3002992  ...   Военно-историческая реконструкция
8             3002993  ...   Военно-историческое моделирование
9             3002994  ...          Военно-патриотический клуб
10            3002995  ...                         Долг памяти
11            3002996  ...                     История авиации
12            3002997  ...                      История оружия
13            3002998  ...   Декоративно-прикладное творчество
14            3002999  ...                               Батик
15            3003000  ...                             Береста
16            3003001  ...                      Бумагопластика
17            3003002  ...  Валяние из шерсти (войлоковаляние)
18            3003003  ...                      Витражное дело
19            3003004  ...              Выжигание (пирография)
20            3003005  ...                           Вышивание
21            3003006  ...                             Вязание
22            3003007  ...                Декоративная игрушка
23            3003008  ...                    Авторская  кукла
24            3003009  ...                    Глиняная игрушка
25            3003010  ...                      Мягкая игрушка
26            3003011  ...                    Народная игрушка
27            3003012  ...                   Театральная кукла
28            3003013  ...                   Текстильная кукла
29            3003014  ...             Декоративная композиция

[30 rows x 3 columns]

In [ ]:
request_hackaton.head(n)

    id_заявления  ... id_услуги
0         989578  ...     39178
1        3571456  ...     39178
2        3571725  ...     39178
3         950963  ...     39178
4         952962  ...     39178
5        3575937  ...     39178
6        3576049  ...     39178
7        3576174  ...     39178
8        3576370  ...     39178
9        3578240  ...     39178
10       3579117  ...     39178
11       3580321  ...     39178
12       3580811  ...     39178
13       3581477  ...     39178
14       3581514  ...     39178
15       3581567  ...     39178
16       3584952  ...     39178
17       3585095  ...     39178
18       3587627  ...     39178
19       3587717  ...     39178
20        951330  ...     39178
21       3679338  ...     39178
22       3679446  ...     39178
23       3679800  ...     39178
24       3680434  ...     39178
25       3680539  ...     39178
26        950776  ...     39178
27        951184  ...     39178
28        954040  ...     39178
29        950976  ...     39178

[30 rows x 9 columns]

In [ ]:
org_hackaton.head(n)

    id_организации  ...                             Метро
0                1  ...                               NaN
1                2  ...                 Краснопресненская
2                2  ...                   Улица 1905 года
3                3  ...                    Красные ворота
4                4  ...               Курская (Кольцевая)
5                6  ...     Курская (Арбатско-Покровская)
6                6  ...               Курская (Кольцевая)
7                6  ...                        Чкаловская
8                7  ...                               NaN
9                8  ...                               NaN
10               9  ...              Крестьянская застава
11              10  ...                           Рижская
12              11  ...                               NaN
13              12  ...                      Серпуховская
14              13  ...                   Улица 1905 года
15              14  ...                      Марксистская
16              15  ...    Парк культуры (Сокольническая)
17              16  ...  Проспект Мира (Калужско-Рижская)
18              16  ...                       Сухаревская
19              17  ...                    Новослободская
20              17  ...                     Менделеевская
21              19  ...     Курская (Арбатско-Покровская)
22              20  ...  Смоленская (Арбатско-Покровская)
23              21  ...                               NaN
24              22  ...                    Красносельская
25              23  ...                           Рижская
26              24  ...                 Краснопресненская
27              24  ...                   Улица 1905 года
28              25  ...                           Полянка
29              26  ...                     Кропоткинская

[30 rows x 5 columns]

In [ ]:
services_hackaton.head(n)

    id_услуги Тип_финансирования  ...  длительность_обучения  единица_длительности
0       39178          бесплатно  ...                 7,0000                   лет
1       39181          бесплатно  ...                 7,0000                   лет
2      212072          бесплатно  ...                 7,0000                   лет
3      212517          бесплатно  ...                 7,0000                   лет
4       39913          бесплатно  ...                 7,0000                   лет
5       39944          бесплатно  ...                 4,0000                   лет
6       40297          бесплатно  ...                 4,0000                   лет
7       40322          бесплатно  ...                 7,0000                   лет
8       44345          бесплатно  ...                 4,0000                   лет
9       44812          бесплатно  ...                 7,0000                   лет
10      45297          бесплатно  ...                 7,0000                   лет
11      45448          бесплатно  ...                 7,0000                   лет
12      87877          бесплатно  ...                 7,0000                   лет
13      88465          бесплатно  ...                 7,0000                   лет
14      39920          бесплатно  ...                 3,0000                   лет
15      41738          бесплатно  ...                 3,0000                   лет
16      24715          бесплатно  ...                 4,0000                   лет
17      39504          бесплатно  ...                 5,0000                   лет
18      39509             платно  ...                 7,0000                   лет
19      39531          бесплатно  ...                 4,0000                   лет
20      39534          бесплатно  ...                 4,0000                   лет
21      39914          бесплатно  ...                 4,0000                   лет
22      39916          бесплатно  ...                 5,0000                   лет
23      39918          бесплатно  ...                 7,0000                   лет
24      39955          бесплатно  ...                 4,0000                   лет
25      39956          бесплатно  ...                 5,0000                   лет
26      39959          бесплатно  ...                 7,0000                   лет
27      40002          бесплатно  ...                 4,0000                   лет
28      40031          бесплатно  ...                 4,0000                   лет
29      40048          бесплатно  ...                 4,0000                   лет

[30 rows x 9 columns]

In [ ]:
MegaRelation_hackaton.head(n)

   id_зачисления  ...  Плановая_дата_окончания_занятий
0        1325954  ...               01.09.2021 0:00:00
1        2879918  ...               01.09.2021 0:00:00
2        2901258  ...               01.09.2021 0:00:00
3        2912724  ...               01.09.2021 0:00:00
4        2912819  ...               01.09.2021 0:00:00
5        2912900  ...               01.09.2021 0:00:00
6        2912974  ...               01.09.2021 0:00:00
7        2913055  ...               01.09.2021 0:00:00
8        2913225  ...               01.09.2021 0:00:00
9        2916369  ...               01.09.2021 0:00:00

[10 rows x 14 columns]

In [ ]:
chytatel.head(n)

    ID читателя Дата рождения
0        366670      10-14-74
1        235264      06-01-78
2        133225      01-06-76
3        556716      01-28-89
4         52086      08-14-55
5         32783      07-21-94
6         19873      05-30-01
7         49059      03-07-12
8        394319      05-22-79
9        557623      03-10-80
10        31068      02-07-62
11       334805      12-03-85
12       558388      03-05-04
13       558970      09-17-84
14       364422      03-15-92
15        33121      02-20-82
16       361167      09-24-83
17       362882      07-19-90
18        13502      10-12-86
19        37574      11-18-81
20       255689      12-29-80
21       121927      01-24-82
22       561690      01-14-86
23       361142      03-07-84
24        22247      02-27-05
25       491850      10-02-07
26       367575      02-14-51
27       555716      09-19-17
28       556717      09-12-81
29        22541      07-05-82

In [ ]:
vyd1.head(n)

    ИД выдачи  ИД читателя  ...        Unnamed: 9  Unnamed: 10
0           1          179  ...          На руках          NaN
1           2          179  ...      Переоформлен          NaN
2           3          179  ...  Размещен в фонде          NaN
3           4          179  ...               NaN          NaN
4           5          179  ...               NaN          NaN
5           6          179  ...               NaN          NaN
6           7          179  ...               NaN          NaN
7           8          163  ...               NaN          NaN
8           9          179  ...               NaN          NaN
9          10          232  ...               NaN          NaN
10         11          232  ...               NaN          NaN
11         12          233  ...               NaN          NaN
12         13          233  ...               NaN          NaN
13         14          232  ...               NaN          NaN
14         15          238  ...               NaN          NaN
15         16          238  ...               NaN          NaN
16         17          238  ...               NaN          NaN
17         18          238  ...               NaN          NaN
18         19          242  ...               NaN          NaN
19         20          244  ...               NaN          NaN
20         21          244  ...               NaN          NaN
21         22          244  ...               NaN          NaN
22         23          244  ...               NaN          NaN
23         24          246  ...               NaN          NaN
24         25          243  ...               NaN          NaN
25         26          243  ...               NaN          NaN
26         27          243  ...               NaN          NaN
27         28          243  ...               NaN          NaN
28         29          243  ...               NaN          NaN
29         30          243  ...               NaN          NaN

[30 rows x 11 columns]

In [ ]:
vyd2.head(n)

    ИД выдачи  ИД читателя  ...        Unnamed: 9  Unnamed: 10
0     6000001       159558  ...          На руках          NaN
1     6000002       159558  ...      Переоформлен          NaN
2     6000003       159558  ...  Размещен в фонде          NaN
3     6000004       348361  ...               NaN          NaN
4     6000005       344222  ...               NaN          NaN
5     6000006       344222  ...               NaN          NaN
6     6000007       344222  ...               NaN          NaN
7     6000008       344222  ...               NaN          NaN
8     6000009       344222  ...               NaN          NaN
9     6000010       344222  ...               NaN          NaN
10    6000011       344222  ...               NaN          NaN
11    6000012       344222  ...               NaN          NaN
12    6000013       344222  ...               NaN          NaN
13    6000014       344222  ...               NaN          NaN
14    6000015       344222  ...               NaN          NaN
15    6000016       344222  ...               NaN          NaN
16    6000017       344222  ...               NaN          NaN
17    6000018       344222  ...               NaN          NaN
18    6000019       344222  ...               NaN          NaN
19    6000020       184762  ...               NaN          NaN
20    6000021       272046  ...               NaN          NaN
21    6000022       348361  ...               NaN          NaN
22    6000023       272046  ...               NaN          NaN
23    6000024       337587  ...               NaN          NaN
24    6000025       348361  ...               NaN          NaN
25    6000026       329126  ...               NaN          NaN
26    6000027       337587  ...               NaN          NaN
27    6000028         6474  ...               NaN          NaN
28    6000029       228522  ...               NaN          NaN
29    6000030       348361  ...               NaN          NaN

[30 rows x 11 columns]

In [ ]:
katal.head(n)

   doc_id                         p100a  ...      p084a p521a
0       1   Устинова Татьяна Витальевна  ...  84(2Рос)6   16+
1       2                           NaN  ...         72   12+
2       3                           NaN  ...         72   12+
3       4                           NaN  ...         72   12+
4       5                           NaN  ...         72   12+
5       6      Тараканов Борис Игоревич  ...  84(2Рос)6   NaN
6       8                           NaN  ...  84(2Рос)6   NaN
7       9                           NaN  ...  84(2Рос)6   NaN
8      10  Федотова Надежда Григорьевна  ...  84(2Рос)6   NaN
9      11            Федорова Екатерина  ...  84(2Рос)6   NaN

[10 rows x 10 columns]

In [ ]:
eksemplar1.head(n)

    Идентификатор экземпляра  ...  Идентификатор сиглы
0                   12488544  ...                314.0
1                   12488546  ...                320.0
2                   12488542  ...                306.0
3                   13671389  ...                308.0
4                    7625486  ...                293.0
5                    7625475  ...                272.0
6                    1375296  ...                 51.0
7                   11840575  ...                196.0
8                   11840570  ...                191.0
9                   11840578  ...                197.0
10                  11840571  ...                192.0
11                  11840572  ...                193.0
12                  11840576  ...                196.0
13                  11840577  ...                196.0
14                  11840581  ...                199.0
15                  11840582  ...                200.0
16                  11840579  ...                198.0
17                  11840573  ...                194.0
18                  11840574  ...                195.0
19                   7625485  ...                294.0
20                   5073820  ...                 57.0
21                   1862081  ...                 58.0
22                   1364159  ...                 56.0
23                   9184853  ...                393.0
24                   9184869  ...                420.0
25                   7625471  ...                264.0
26                   7625484  ...                291.0
27                   4462738  ...                185.0
28                   6236599  ...                157.0
29                  14979986  ...                462.0

[30 rows x 6 columns]

In [ ]:
eksemplar2.head(n)

    Идентификатор экземпляра  ...  Идентификатор сиглы
0                    2830404  ...                112.0
1                    2830403  ...                113.0
2                    2781735  ...                 81.0
3                    2781737  ...                 87.0
4                    2781738  ...                 87.0
5                    2781734  ...                 80.0
6                    2781736  ...                 71.0
7                    1657704  ...                 76.0
8                    1657702  ...                 67.0
9                    2910774  ...                 90.0
10                   1657699  ...                 69.0
11                   1657701  ...                 64.0
12                   1657700  ...                 95.0
13                   1657708  ...                 91.0
14                   1657706  ...                 69.0
15                  11410244  ...                204.0
16                   1657703  ...                 72.0
17                   1657709  ...                 93.0
18                   1657711  ...                 94.0
19                  13060701  ...                355.0
20                   2800053  ...                129.0
21                   2800046  ...                115.0
22                   2800048  ...                136.0
23                   2781746  ...                137.0
24                   2781745  ...                142.0
25                   2800056  ...                120.0
26                   2800057  ...                126.0
27                   2800061  ...                118.0
28                   3504753  ...                106.0
29                   3504757  ...                104.0

[30 rows x 6 columns]

In [ ]:
meropr.head(n)

       id  ...                                  Целевая аудитория
0       5  ...                                                NaN
1      12  ...          работающая молодежь, взрослые, пенсионеры
2    3179  ...  школьники, работающая молодежь, студенческая м...
3     486  ...               дети дошкольного возраста, школьники
4    2100  ...  дети дошкольного возраста, школьники, работающ...
5     254  ...               дети дошкольного возраста, школьники
6      78  ...                                                NaN
7   10257  ...  дети дошкольного возраста, школьники, работающ...
8    1593  ...  дети дошкольного возраста, школьники, работающ...
9   12167  ...  дети дошкольного возраста, школьники, работающ...
10   1273  ...  дети дошкольного возраста, школьники, работающ...
11   1278  ...  дети дошкольного возраста, школьники, работающ...
12   1279  ...  дети дошкольного возраста, школьники, работающ...
13   1280  ...  дети дошкольного возраста, школьники, работающ...
14   1282  ...  дети дошкольного возраста, школьники, работающ...
15   1285  ...  дети дошкольного возраста, школьники, работающ...
16   2706  ...  дети дошкольного возраста, школьники, работающ...
17   2707  ...  дети дошкольного возраста, школьники, работающ...
18   2708  ...  дети дошкольного возраста, школьники, работающ...
19   2709  ...  дети дошкольного возраста, школьники, работающ...
20   2710  ...  дети дошкольного возраста, школьники, работающ...
21     37  ...  дети дошкольного возраста, школьники, работающ...
22   2711  ...  дети дошкольного возраста, школьники, работающ...
23  10087  ...  дети дошкольного возраста, школьники, работающ...
24  10093  ...  дети дошкольного возраста, школьники, работающ...
25  10096  ...  дети дошкольного возраста, школьники, работающ...
26  10097  ...  дети дошкольного возраста, школьники, работающ...
27  10099  ...  дети дошкольного возраста, школьники, работающ...
28     44  ...  дети дошкольного возраста, школьники, работающ...
29     45  ...  работающая молодежь, студенческая молодежь, вз...

[30 rows x 25 columns]